# config/BUILD

config_setting(
    name = "arm_none_compatible",
    constraint_values = [
        "@platforms//cpu:arm",
        "@platforms//os:none",
    ],
)

config_setting(
    name = "armv7-m_none_compatible",
    constraint_values = [
        "@platforms//cpu:armv7-m",
        "@platforms//os:none",
    ],
)
